### ISSUE TITLE
Pressing "Refresh all Gradle projects" looses Vaadin dependencies

### ISSUE THREAD

**Issue by johndevs** [johndevs/gradle-vaadin-plugin#107]
Using the JetGradle tool Window in Intellij and pressing "refresh all projects" will loose the vaadin dependencies as JetGradle does its own magic and does not rely on the idea plugin. 

Workaround: When adding new dependencies always run the 'idea' task from the idea plugin instead of refreshing from the JetGradle window.

**Comment by livotov** [comment]
IDEA 14 also looses vaadin deps when automatic dependency management is turned on in vaadin fradle plugin. Had to switch back to manual deps management, because adding "providedCompile 'com.vaadin:vaadin-client:7.3.0'" into the gradle file helps IDEA to see the vaadin classes but does not allow vaadin gradle plugin to package all the dependencies into the release war

**Comment by johndevs** [comment]
The changes to the dependency injection that will be introduced in **0.11**  (dependencies are injected as default dependencies instead of injected in afterEvaluate ) fixes this.
