### ISSUE TITLE
Vaadin Spring Dependency

### ISSUE THREAD

**Issue by kjordan2001** [johndevs/gradle-vaadin-plugin#170]
I was using the apply from 0.9-SNAPSHOT, but since the website for that is down (gone?), I switched to the newer versions available on plugins.gradle.org.  However I can't get the newer versions to work.  It seems as though it's incorrectly applying the Vaadin version to the vaadin-spring add-on as a dependency since I'm getting an error: Could not find com.vaadin:vaadin-spring:7.4.3.  vaadin-spring's latest version is 1.0.0.beta1 and not in line with the latest Vaadin versions.  The last version of this plugin I can get to not give the error is 0.9.2 but that version ends up not generating my widgetset.

**Comment by johndevs** [comment]
> I was using the apply from 0.9-SNAPSHOT, but since the website for that is down (gone?)

I'm currently moving the snapshot repository over to another service provider due to the increased traffic of the plugin. It should be up again very soon.

>It seems as though it's incorrectly applying the Vaadin version to the vaadin-spring add-on

The issue you are seeing has been fixed in a63df54fcc25dc6ad55bf4e4fc8a4b1703c8bad7 but it hasn't been released yet. That is why the snapshot works but the latest release does not.
