### ISSUE TITLE
 Gradle sync failed: Could not find vaadin-server.jar (com.vaadin:vaadin-server:7.5.10)

### ISSUE THREAD

**Issue by Alchemist0823** [johndevs/gradle-vaadin-plugin#215]
Gradle sync failed: Could not find vaadin-server.jar (com.vaadin:vaadin-server:7.5.10).
Searched in the following locations:
https://jcenter.bintray.com/com/vaadin/vaadin-server/7.5.10/vaadin-server-7.5.10.jar

**Comment by vyazelenko** [comment]
No wonder, Since on this URL https://jcenter.bintray.com/com/vaadin/vaadin-server/7.5.10/ **there is no** `vaadin-server-7.5.10.jar`. Currently there are only:
* `vaadin-server-7.5.10-javadoc.jar`
* `vaadin-server-7.5.10-sources.jar`
* `vaadin-server-7.5.10.pom`

However if you check *Files* view in https://bintray.com/bintray/jcenter/com.vaadin%3Avaadin-server/7.5.10/view. Then you will find all files:
![image](https://cloud.githubusercontent.com/assets/696855/11590390/368c24f2-9a90-11e5-82a2-7b14d7b3c5c9.png)

**Comment by vyazelenko** [comment]
I've raised this issue with Bintray support. Waiting for their response...

**Comment by vyazelenko** [comment]
@Alchemist0823 As a workaround you can use `mavenCentral` repository instead of `jcenter` (or at least put it before `jcenter`). Or define Vaadin version explicitly in plugin to something other than **7.5.10**.

**Comment by johndevs** [comment]
Looks like Bintray has fixed the issue now. Thanks for the report!
