### ISSUE TITLE
vaadin.gwt.outputDirectory error

### ISSUE THREAD

**Issue by neopsis** [johndevs/gradle-vaadin-plugin#223]
Does not work for me:

vaadin.gwt.outputDirectory = "src/main/resources"
...
> Cannot cast object 'src/main/resources' with class 'java.lang.String' to class 'java.io.File'

**Comment by christoph-frick** [comment]
why do you want to generate those into the source dir?  isn't the build itself some saner place?  e.g. https://github.com/christoph-frick/springboot-groovy-vaadin-starter/blob/master/gradle/springboot-vaadin-fixes.gradle#L14

**Comment by neopsis** [comment]
The directory was only an example. For me the important part of your answer is the solution:

   vaadin.gwt.outputDirectory = file('src/main/resources')

Thank you.

**Comment by christoph-frick** [comment]
since other options ending in `Directory` allow strings (e.g. `themesDirectory`) this is actually a little bit confusion.  the var in the GWTConfiguration is `File` - i wonder why groovy does not try to coerce it.  the only way around this I can think of, that might not break backward compatibility is changing type to `Object` and do an `File` cast in `Util`?

**Comment by johndevs** [comment]
Instead of Object we can also change it dir
