### ISSUE TITLE
Charts License

### ISSUE THREAD

**Issue by trisbez** [johndevs/gradle-vaadin-plugin#254]
Hello-

   We use the Charts plug-in in our application, is there a way that we can apply the license without having the vaadin.charts.developer.license file present in our home directory?  We would like to be able to pass this in as part of the build or have it specified in our build.gradle file.

  Thanks in advance!

**Comment by johndevs** [comment]
You can do that by adding the following to your build.gradle:
```
vaadinCompile {
    jvmArgs = ["-Dvaadin.charts.developer.license=${System.properties['vaadin.charts.developer.license']}"]
}
````
Just run `` gradle -Dvaadin.charts.developer.license=<you license> ...`` and it will work. Of course you can also add it directly to the build.gradle as well instead of reading it from a system property, but that will expose the license to everyone using the repository which is not optimal.

**Comment by trisbez** [comment]
Wonderful! Thanks much!
