### ISSUE TITLE
Please make the logToConsole = true the default option

### ISSUE THREAD

**Issue by mvysny** [johndevs/gradle-vaadin-plugin#317]
When developing with gradle vaadinRun, the console log is hidden and is redirected to a file. However, I am unable to find the file - it may be hidden somewhere in Jetty working directory but it's not clear where that is. Also, when developing, it is way better to see immediate feedback in the console, rather than tail a file.

Therefore, please consider making the logToConsole default to true.

**Comment by johndevs** [comment]
This is intentional and follows the guidelines of the standard Gradle plugins. By default the minimum amount of information is outputted to the console and you need to provide the Gradle build with either the ``--info``, ``--stacktrace`` or ``--debug`` options to get a better log. 

But what we could do is automatically turn on **logToConsole** if any of those parameters are provided for the build.

**Comment by mvysny** [comment]
Sticking to Gradle guidelines of course makes sense, no objections there. Yet, before you implement it as you described, please consider this: this mode of run (./gradlew vaadinRun) is not used in a standard way (the production mode), to build an artifact; it is in fact not slated to end unless killed by the user. Instead, it is used for the developer to develop stuff (in a development mode), where the developer benefits from seeing all program output (including the debugging output). I think that the developer *expects* to see as much as possible; seeing otherwise or no output is thus more surprising.
Therefore, by the principle of least surprise, I would expect the console log to be visible by default. What do you think?

**Comment by mvysny** [comment]
That's too bad. With Maven's `mvn jetty:run` I can see the Jetty's output directly in the console by default, without having to configure anything in `pom.xml`. I was kinda hoping to have this kind of functionality in Gradle as well...

**Comment by mvysny** [comment]
Please, I ask you to reconsider your decision - Gretty with the default setting prints everything (stderr stdout and logging) correctly to the console.

**Comment by mvysny** [comment]
Because of this issue, I am forced to use Gretty for the https://github.com/mvysny/karibu-helloworld-application . The developer must see logging output in the console; however with Gradle Vaadin Plugin's built-in Jetty nor Payara the logging output is not printed to the console as opposed with Gretty.

**Comment by DALDEI** [comment]
+1000000 to mvysyn.   Until gradle comes out with a different fundamental *mode* of operations, there is no use case I can conceive of where hiding the log messages for this action has anything but very large net negative value.  Conventions are "conventions" -- meaning that's what you do when there is no other compelling reason to do otherwise.  In this case there is *only* compelling reasons to do otherwise and no imaginable reason not to show error logs.  Of course my imagination is less then infinite, so if a reason did come up (counter to the 'convention' of showing errors) then having an option to hide them is a potential feature ... or perhaps not, as its more likely the user ran the wrong command and should be told so.
