### ISSUE TITLE
Issues with v-leaflet add-on

### ISSUE THREAD

**Issue by mstahv** [johndevs/gradle-vaadin-plugin#324]
John, do you have any idea why people can't compile widgetset with v-leaflet?

https://vaadin.com/forum#!/thread/14319851/15040559

**Comment by johndevs** [comment]
@mstahv At least one thing I found was that the leaflet addon inherits the old default widgetset. That won't work with Vaadin 8 that does not include the old one. 

The latest Gradle plugin defaults to latest Vaadin 8 version so all users trying out the gradle plugin and leaflet will get a compilation failure because of this. Could you update the addon to become V8 compliant?

**Comment by mstahv** [comment]
Ah, maybe that is the issue indeed. There actually is a Vaadin 8 compatible version done by Ilia, but didn't cut a release as started waiting, and waiting, and waiting for beta2 :-)

**Comment by johndevs** [comment]
Alright, closing this then :)

**Comment by lucasmontec** [comment]
Sorry to re-open this issue but as I'm unable to compile v-leaflet with this plugin I think its the same context, eventhough it is not the exact same problem. Check this issue out: https://github.com/mstahv/v-leaflet/issues/187
