### ISSUE TITLE
New beta version available

### ISSUE THREAD

**Issue by kiru** [johndevs/gradle-vaadin-plugin#414]
Hello, 

I have updated to the latests stable version 1.1.12 and get the following message:

> 
> Using Gradle Vaadin Plugin 1.1.12
> !! A newer version of the Gradle Vaadin plugin is available, please upgrade to 1.2.0-beta1 !!
> 
> 
> The Gradle Vaadin plugin has changed id and has moved to a new location. This plugin
> will no longer recieve any updates.
> 
> Please update the plugin by using the following statement in your build.gradle
> 
> plugins {
>     id 'com.devsoap.plugin.vaadin' version '1.2.0-beta1'
> }
> 
> Please see https://plugins.gradle.org/plugin/com.devsoap.plugin.vaadin for further
> instructions of how to apply the new plugin to your build or visit the plugin wiki
> page at https://github.com/johndevs/gradle-vaadin-plugin/wiki.

Is it possible to disable this message? I don't want to update to a beta version, I'm pretty happy with the latests stable version.

**Comment by johndevs** [comment]
The message is intentional to ensure that everybody is aware that they are using a old version of the plugin that will not receive any new updates or fixes. It is an annoyance you will have to live with if you want to stay with the old plugin. 

The new version is in beta right now, but will soon become the next stable version and I already think it would be safe to update to it. 

In 1.2 the version check can be disabled but in 1.1 it can't be.

**Comment by kiru** [comment]
I see your point, but it does not make any sense to show a beta version, maybe a better solution would be show this message only for stable versions.

**Comment by johndevs** [comment]
The version shown is dynamic and will always show the **latest** version. The latest version now happens to be beta, but that won't last long :)

**Comment by kiru** [comment]
Sure, the beta version is not shown long, but imagine if you have an application with few dependencies and each of them shows this message at startup ( that is really what bothers me ). 
Anyway, I'll be happy to disable it in my project with version 1.2.
