### ISSUE TITLE
Using Vaadin plugin forces war packaging in Buildship

### ISSUE THREAD

**Issue by peterl1084** [johndevs/gradle-vaadin-plugin#441]
(Not sure if this is really a bug in Gradle plugin, sorry if not)

When using Vaadin Gradle Plugin (latest version) with Vaadin 8.1 project, where Gradle environment is configured as multi module project having a separate artifact for widgetset, the Eclipse imported Gradle project always forces the widgetset project to be war packaged rather than jar.

I'm having following structure in my project

root (folder with build file)
 -  app-deploy (war, has all other projects as dependency)
 -  app-ui (jar)
 -  app-module-1...n (jars)
 -  app-widgetset (jar, applies vaadin plugin)

Out of the above I would want all the nested artifacts to be of type jar, except for the deploy project, that then aggregates all other dependencies into a war.

When applying the Gradle Vaadin Plugin to app-widgetset project, it (when imported to eclipse) always sets the app-widgetset's artifact type to war, rather than expected jar.

I believe this is due to the WarPlugin applied on the project in (https://github.com/johndevs/gradle-vaadin-plugin/blob/master/src/main/groovy/com/devsoap/plugin/GradleVaadinPlugin.groovy#L243)

Looking from Eclipse's Buildship (2.1.1) the task list always has the last task of type war whereas for all other projects war task is not present.

I've also tried to disable the war by saying war.enabled = false without success.

From CLI with simple gradle build everything works as expected giving the above structure as a single war file containing just jars (as expected)

Is the war plugin necessary for Vaadin plugin? I guess Eclipse's Gradle integration assumes that if war plugin is applied the artifact type will always be war

**Comment by ITman1** [comment]
I would also welcome to some configuration property which would make war packing optional - at least when spring boot is used.

Right now I had to do something similar:

```
war.enabled = false
afterEvaluate { project ->
    configurations.archives.artifacts.removeAll { it.archiveTask.is war }
}
```

**Comment by johndevs** [comment]
@ITman1 If you use spring boot by using the spring boot Gradle plugin then the war plugin should not be applied if you apply the spring boot plugin before the gradle plugin. Check out https://github.com/johndevs/gradle-vaadin-plugin/wiki/Creating-a-Spring-Boot-Project for an example.

@peterl1084 By default the Gradle Vaadin plugin assumes you are building applications instead of libraries which is why the war plugin is applied (except in the spring-boot case above). To fix this issue the plugin would need to be split in two, ``-core`` and ``-application`` (which would depend on -core) plugins which would allow the developer to select if he only wants to the core functionalities of the plugin or if he also wants the application specific functionalities as well. That could be a nice enhancement at some point.

**Comment by xenoterracide** [comment]
hmm.... I think this will be a problem for me...
