### ISSUE TITLE
Probably wrong order of styles.scss imports when creating new theme via plugin

### ISSUE THREAD

**Issue by livotov** [johndevs/gradle-vaadin-plugin#474]
It currently puts addons.scss first but should not the theme scss import be the first one ?
Because the base (valo) theme is included from mytheme.scss, it should go first, so any base theme variables -dependent addons can see and use these variables.

```
@import "addons.scss";
@import "mytheme.scss";

/* This file prefixes all rules with the theme name to avoid causing conflicts with other themes. */
/* The actual styles should be defined in mytheme.scss */
.mytheme {
  @include addons;
  @include mytheme;
}
```

Just got such an issue while including another custom addon to the project - it depends on Valo theme and uses the following definition: $drawer-background-color: lighten($v-background-color, 0.1) !default;

Since in plugin-generated theme file addons import goes first, the valo's v-background-color variable was not defined at that moment, causing theme compiler to crash with NPE when processing addon's scss...

**Comment by johndevs** [comment]
This is a chicken-and-egg problem I'm afraid. 

If the theme import is first then you will not be able to override the theme provided by an addon in your application theme. This is something you usually want to do to make the addon style fit in to your application theme.  If the theme import is moved after the addon, as it is now, then addon themes cannot use Valo variables.

I don't really have a solution for this as either way it will break someones app. The first scenario is in my opinion more common, and the Vaadin IDE integrations do the same thing, which is why it is implemented as it is now. Any good ideas of solving both scenarios are welcome :)

**Comment by appreciated** [comment]
[The maven archetype `vaadin-archetype-application` does it the way @livotov describes it](https://github.com/vaadin/archetypes/blob/master/vaadin-archetype-application/src/main/resources/archetype-resources/src/main/webapp/VAADIN/themes/__themeName__/styles.scss).

I don't have concrete numbers 🙁 but aren't the most projects indirectly generated via the maven archetypes even in IDE's?

> If the theme import is first then you will not be able to override the theme provided by an addon in your application theme. This is something you usually want to do to make the addon style fit in to your application theme. If the theme import is moved after the addon, as it is now, then addon themes cannot use Valo variables.

Are you sure that this is always the case? From my experience this will only happen if you don't use `@mixin` but go straight for class definitions. Which hopefully is rarely the case. If addons rely on properly written sass this should be working without any problem since the `@include` is in the order:
```
.mytheme {
  @include addons;
  @include mytheme;
}
```

**Comment by johndevs** [comment]
As the theme is just generated either when doing ``vaadinCreateProject`` or when explicitly running ``vaadinCreateTheme`` and the theme is never updated I think we can try to change it in the next minor version and see how it goes.
