### ISSUE TITLE
Plugin imports vaadin-client 8.0.* and vaadin-server 8.1.*

### ISSUE THREAD

**Issue by juhawilppu** [johndevs/gradle-vaadin-plugin#496]
My build.gradle contains this
```
dependencyManagement {
    imports {
        mavenBom "com.vaadin:vaadin-bom:8.0.6"
    }
}
```
which causes vaadin-gradle-plugin 1.3.0 to download vaadin-client 8.0.6 but it downloads vaadin-server 8.1.7 and build fails. This happens because of ``vaadin.defaultVersion=8.1.+`` defined here https://github.com/johndevs/gradle-vaadin-plugin/blob/f4278a758bf0e4ad0b870ff0f4f08338823c01ff/gradle.properties .

The solution/workaround is to add this to build.gradle
```
vaadin {
    version '8.0.6'
}
```
but it still feels like a bug. I think the vaadin-bom:8.0.6 should affect both vaadin-client and vaadin-server.

**Comment by nikkijuk** [comment]
I did try with vaadin version 8.2.0.rc1 and at that point theme was suddenly 8.1.6. It seemed to me that for some thing plugin used latest version instead one defined in gradle build file, but I didn't start to analyze it deeply.

**Comment by mvysny** [comment]
This may be actually a bug in the `io.spring.dependency-management` plugin which may not be somehow compatible with the dynamic nature of how gradle-vaadin-plugin adds dependencies. Forcing the same version both for bom and for vaadin-gradle-plugin looks like a good idea.

**Comment by johndevs** [comment]
The spring dependency management plugin overrides the Gradle dependency management concepts and adds Mavenish concepts that always does not work reliably. If you don't have a specific usecase for it I usually advice people to leave it out.

That said, the issue seems to be that the spring plugin uses a custom ``resolutionStrategy``. So you just need to ensure that ``vaadin`` plugin is applies **after** the spring management plugin. so it gets a chance of syncronizing the dependencies. 

This should fix your issue:
```
plugins {
    id "io.spring.dependency-management" version "1.0.4.RELEASE"
    id 'com.devsoap.plugin.vaadin' version '1.3.0'   
}
```

However, I'm curious why you need the import at all as the plugin will get the necessary dependencies for you?
