### ISSUE TITLE
vaadinCompile error 'must override or implement a supertype method'

### ISSUE THREAD

**Issue by hellectronic** [johndevs/gradle-vaadin-plugin#507]
Hello Community,

I hope to find some directions on my problem setting up a Vaadin Gradle project with Vaadin Addons.
This must be a "simple" versioning issue, but my skills to find the cause are limited.

The following information in provided as gist:

- Output of gradle build clean: https://gist.github.com/hellectronic/a7503817a0086f54a6e42df469abb3a9
- gradle dependecies output: https://gist.github.com/hellectronic/b4c15e5eeb472f7825e98a4ed07d7669
- my build file: https://gist.github.com/hellectronic/eb29427b094e3058c432970bcca67de5

The build output
```
Errors in 'jar:file:/C:/Users/george/.gradle/caches/modules-2/files-2.1/com.vaadin/vaadin-client/8.3.1/976bbfe33faa07d5880a30903b21d0b6e7199146/vaadin-client-8.3.1.jar!/com/vaadin/client/widget/treegrid/events/TreeGridDoubleClickEvent.java'
Line 57: The method ignoreEventFromTarget(Grid<?>, Element) of type TreeGridDoubleClickEvent must override or implement a supertype method
Line 60: The method ignoreEventFromTarget(Grid<capture#1-of ?>, Element) is undefined for the type GridDoubleClickEvent
Tracing compile failure path for type 'com.vaadin.client.ui.notification.NotificationConnector'
Errors in 'jar:file:/C:/Users/george/.gradle/caches/modules-2/files-2.1/com.vaadin/vaadin-client/8.3.1/976bbfe33faa07d5880a30903b21d0b6e7199146/vaadin-client-8.3.1.jar!/com/vaadin/client/ui/notification/NotificationConnector.java'
Line 36: Type mismatch: cannot convert from Class<Notification> to Class<? extends Connector>
Line 49: The method showNotification(ApplicationConnection, UIDL) in the type VNotification is not applicable for the arguments (ApplicationConnection, String, String, boolean, String, String, Position, int)
Aborting compile due to errors in some input files
:vaadinCompile FAILED
``` 

I assume that some dependency has the wrong version. First there was an error with GWT regarding a wrong javax.validation-api version. After fixing it (I hope in a _good_ way), this error shows up.

It would be great to get some direction for the build file configuration. Is it correct?

**Comment by johndevs** [comment]
Hi,

The issue you are seeing is most likely because you are getting multiple versions of the dependencies on your classpath. 

Here are a few things you can try:

1) The Vaadin plugin will automatically add the required dependencies so you can remove all dependencies you have with the group "com.vaadin". They will just cause problems and pull in duplicates to your classpath.

1) The same with the "javax.validation-api" and javax-validation.version. You don't need that, if you have configured the project correctly the validation-api will not be a problem.

1) Instead of having your own version property of vaadin, use the vaadin extension to set the vaadin version. Like so: 
    ```
    vaadin {
        version '8.3.1'
        push true
    }
    ```
    If you need to configure the vaadin spring boot dependency version then you can add
    ```
    vaadinSpringBoot {
        starterVersion  '3.0.0'
    }
    ```
1) The Temp folder issue is no longer relevant, it has been fixed a while ago so you can remove the whole ``vaadinCompile`` configuration.

1) You are applying the spring boot plugin in both the ``buildscript{}`` block as well as in the ``plugins{}`` block. You can safely remove the ``buildscript{}`` block.

In essence, when working with spring boot and the vaadin plugin the only required things to configure is the following plugins block. 
```
plugins {  
    id 'org.springframework.boot' version '1.5.9.RELEASE'
    id 'com.devsoap.plugin.vaadin' version '1.3.1'
}
```
The order of the plugins *is important*! The vaadin plugin needs to be *after* the spring boot plugin to work corretly.

When you have this ``plugins{}`` block, all required dependencies are then added automatically for you and the plugin will configure the project for you. The only things I see you should keep in the ``dependencies{}`` block is something like this:
```
dependencies {	
	
	// enable log4j2 alternativ spring logging
	compile('org.springframework.boot:spring-boot-starter-log4j2')
	// disruptor is needed for async log4j2
	compile('com.lmax:disruptor:3.3.7')

	compile("org.vaadin.crudui:crudui:2.3.0")
	compile("org.vaadin.addons:vaadin-grid-util:2.1.1")
	compile("com.github.appreciated:app-layout-addon:0.9.20")

	compile("org.springframework.boot:spring-boot-starter-data-jpa")
	compile("com.h2database:h2")

	testCompile('org.springframework.boot:spring-boot-starter-test')
}
```
The plugin will compile the widgetset, include the correct dependencies in correct configurations without you adding them manually to the dependencies block. 

Hope this helps

**Comment by hellectronic** [comment]
Thank you for the fast reply. I will try the suggestion and write about the results :)

**Comment by hellectronic** [comment]
Thank you very much! It was not clear to me that the plugin order was important and that the vaadin plugin will manage everything for me.
I can build and start the project with bootRun now. No errors.
Closing the ticket.
